//===BEGIN===
  var CONSTANT = {
    BASE_Z_INDEX: 100000,

    CONTROL_BAR_HEIGHT: 40,

    SIDE_PLAYER_WIDTH: 400,
    SIDE_PLAYER_HEIGHT: 225,

    BIG_PLAYER_WIDTH: 896,
    BIG_PLAYER_HEIGHT: 480,

    RIGHT_PANEL_WIDTH: 320,
    BOTTOM_PANEL_HEIGHT: 240
  };


